# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Angular Js / Node.js Package

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Angular App
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST}} # ip address of the server you wish to ssh into
#           key: ${{secrets.ATLAS_ANGULAR_SSH_PRIVATE}} # public or private key of the server 
          username: ${{secrets.SSH_USERNAME}} # user of the server 
          password: ${{secrets.SSH_PASSWORD}} # password of the server 
          script: | 
            mkdir test
            cd test
            npm install
            npm install -g @angular/cli
            git clone git@github.com:tripletens/atlas_angular.git
            cd atlas_angular
            ng build
            echo 'Deployment successful to digital ocean.'
#           passphrase: ${{secrets.SSH_PASSWORD}}

